/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import exaprac2.trabajadores;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell
 */
public class Registro_trabajadores extends javax.swing.JFrame {

    String [] columnas = {"CODIGO","NOMBRE EMPLEADO","SALARIO HORA","HORAS TRABAJADAS"};
    DefaultTableModel modelo = new DefaultTableModel(columnas, 0);
    
     //crear una lista para guardar los registros
    List<trabajadores> datos = new ArrayList<trabajadores>();
    
    //variable para ir totalizando
    double total=0;
    
    
    
    
    
    
    public Registro_trabajadores() {
        initComponents();
        
        
         //aplicar el modelo a la tabla
        tbldatos.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnombres = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtsalario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txthoras = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldatos = new javax.swing.JTable();
        btnagregar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbltotal = new javax.swing.JLabel();
        btnsalir = new javax.swing.JButton();
        lbleee = new javax.swing.JLabel();
        lblempleado = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Examen practico 2");
        setIconImages(null);

        jLabel1.setFont(new java.awt.Font("Algerian", 3, 24)); // NOI18N
        jLabel1.setText("::::REGISTRO DE PLANILLA DE TRABAJADORES:::::");

        jLabel2.setFont(new java.awt.Font("Sitka Heading", 1, 16)); // NOI18N
        jLabel2.setText("CODIGO:");

        jLabel3.setFont(new java.awt.Font("Sitka Heading", 1, 16)); // NOI18N
        jLabel3.setText("NOMBRE:");

        jLabel4.setFont(new java.awt.Font("Sitka Heading", 1, 16)); // NOI18N
        jLabel4.setText("SALARIO HORAS");

        jLabel5.setFont(new java.awt.Font("Sitka Heading", 1, 16)); // NOI18N
        jLabel5.setText("HORAS TRABAJADAS");

        tbldatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbldatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbldatos);

        btnagregar.setFont(new java.awt.Font("Sitka Heading", 1, 16)); // NOI18N
        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/aceptar.png"))); // NOI18N
        btnagregar.setText("AGREGAR");
        btnagregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnagregarMouseClicked(evt);
            }
        });

        btneliminar.setFont(new java.awt.Font("Sitka Heading", 1, 16)); // NOI18N
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/eliminar.png"))); // NOI18N
        btneliminar.setText("ELIMINAR");
        btneliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btneliminarMouseClicked(evt);
            }
        });

        btnmodificar.setFont(new java.awt.Font("Sitka Heading", 1, 16)); // NOI18N
        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/modificar.png"))); // NOI18N
        btnmodificar.setText("MODIFICAR");
        btnmodificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmodificarMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Sitka Heading", 1, 16)); // NOI18N
        jLabel6.setText("$");

        jLabel7.setFont(new java.awt.Font("Sitka Heading", 1, 16)); // NOI18N
        jLabel7.setText("TOTAL DE PLANILLA ");

        lbltotal.setFont(new java.awt.Font("Sitka Heading", 1, 16)); // NOI18N
        lbltotal.setText("0.0");

        btnsalir.setFont(new java.awt.Font("Sitka Heading", 1, 16)); // NOI18N
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/salir.png"))); // NOI18N
        btnsalir.setText("SALIR");
        btnsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsalirMouseClicked(evt);
            }
        });

        lbleee.setFont(new java.awt.Font("Sitka Heading", 1, 16)); // NOI18N
        lbleee.setText("EMPLEADO QUE MAS GANO ES:");

        lblempleado.setFont(new java.awt.Font("Sitka Heading", 1, 16)); // NOI18N
        lblempleado.setText(".");
        lblempleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblempleadoMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Sitka Heading", 1, 16)); // NOI18N
        jLabel8.setText("RICARDO ANTONIO MERINO RUANO #287318");

        jLabel9.setFont(new java.awt.Font("Sitka Heading", 1, 16)); // NOI18N
        jLabel9.setText("DANIEL ENRIQUE HERNANDEZ RAMOS #225020");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbleee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltotal)
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btnagregar)
                .addGap(25, 25, 25)
                .addComponent(btnmodificar)
                .addGap(37, 37, 37)
                .addComponent(btneliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnombres, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtsalario, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txthoras, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtnombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtsalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txthoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(lbltotal)
                        .addComponent(jLabel7))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbleee)
                        .addComponent(lblempleado)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmodificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmodificarMouseClicked
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Desea modificar el registro?","Titulo",
            JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE)==0){
        trabajadores prod = new trabajadores();

        //cargar el objeto con datos
        prod.setCodigo(Integer.parseInt(txtcodigo.getText()));
        prod.setNombres(txtnombres.getText());
        prod.setSalario_hora(Double.parseDouble(txtsalario.getText()));
        prod.setCantidad_horas_trabajadas(Integer.parseInt(txthoras.getValue().toString()));

        //hacer la modificacion en la lista
        //buscar el index que se va modificar
        int index =0;
        for(trabajadores p : datos){
            if(p.getCodigo() == prod.getCodigo()){
                break;
            }
            index++;
        }
        //hacer la modificacion
        datos.set(index, prod);

        cargar();
        limpiar();
        retotalizar();
        }
    }//GEN-LAST:event_btnmodificarMouseClicked

    private void btneliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneliminarMouseClicked
        // TODO add your handling code here:

        if(JOptionPane.showConfirmDialog(this, "Desea eliminar el registro?","Titulo",
            JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE)==0){

        trabajadores prod = new trabajadores();

        //cargar el objeto con datos
        prod.setCodigo(Integer.parseInt(txtcodigo.getText()));
        prod.setNombres(txtnombres.getText());
        prod.setSalario_hora(Double.parseDouble(txtsalario.getText()));
        prod.setCantidad_horas_trabajadas(Integer.parseInt(txthoras.getValue().toString()));

        //buscar el index que se va modificar
        int index =0;
        for(trabajadores p : datos){
            if(p.getCodigo() == prod.getCodigo()){
                break;
            }
            index++;
        }

        datos.remove(index);
        }
        cargar();
        retotalizar();
        limpiar();

    }//GEN-LAST:event_btneliminarMouseClicked

    private void btnagregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnagregarMouseClicked
        // TODO add your handling code here:

        trabajadores  prod = new trabajadores();

        //cargar el objeto con datos
        prod.setCodigo(Integer.parseInt(txtcodigo.getText()));
        prod.setNombres(txtnombres.getText());
        prod.setSalario_hora(Double.parseDouble(txtsalario.getText()));
        prod.setCantidad_horas_trabajadas(Integer.parseInt(txthoras.getValue().toString()));

        //meter el registro a la lista
        datos.add(prod);
        cargar();
        limpiar();

    }//GEN-LAST:event_btnagregarMouseClicked

    private void tbldatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldatosMouseClicked
        // TODO add your handling code here:

        // TODO add your handling code here:
        txtcodigo.setText(tbldatos.getValueAt(tbldatos.getSelectedRow(), 0).toString());
        txtnombres.setText(tbldatos.getValueAt(tbldatos.getSelectedRow(), 1).toString());
        txtsalario.setText(tbldatos.getValueAt(tbldatos.getSelectedRow(), 2).toString());

        SpinnerNumberModel smodel = new SpinnerNumberModel();
        smodel.setMaximum(100);
        smodel.setMinimum(0);
        smodel.setValue(Integer.parseInt(tbldatos.getValueAt(tbldatos.getSelectedRow(), 3).toString()));
        txthoras.setModel(smodel);
    }//GEN-LAST:event_tbldatosMouseClicked

    private void lblempleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblempleadoMouseClicked
        // TODO add your handling code here:

        trabajadores prod = new trabajadores();

    }//GEN-LAST:event_lblempleadoMouseClicked

    private void btnsalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalirMouseClicked
        // TODO add your handling code here:

        if(JOptionPane.showConfirmDialog(this, "Desea cerrar sesion?","Titulo",
            JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE)==0){
        dispose();
        }
    }//GEN-LAST:event_btnsalirMouseClicked

    
    
     public void cargar(){
           //cargar la lista de modelo, luego el modelo a la tabla 
        modelo.setNumRows(0);//limpiando el modelo
       // metiendo los datos al modelo
       for(trabajadores p : datos){
           
            modelo.addRow(new Object[] {p.getCodigo(),p.getNombres(),
             p.getSalario_hora(), p.getCantidad_horas_trabajadas()});
            
             //aplicar el modelo a la tabla
        tbldatos.setModel(modelo);
        
        total += (Integer.parseInt(txthoras.getValue().toString()))*
                (Double.parseDouble(txtsalario.getText()));
        
        lbltotal.setText(String.valueOf(total));
           
       }   
    }  
     public void limpiar(){
        txtcodigo.setText("");
        txtnombres.setText("");
        txtsalario.setText("");
        txthoras.setValue(0);
    }
     
     public void retotalizar(){
        total =0;
        for(int i=0; i < tbldatos.getRowCount(); i++){
            total += (Double.parseDouble(tbldatos.getValueAt(i, 2).toString() ))*
                    (Integer.parseInt(tbldatos.getValueAt(i, 3).toString()));             
        }
        lbltotal.setText(String.valueOf(total));  
    }
     
     
     private void otraCosa(java.awt.event.MouseEvent evt) {                          
        // TODO add your handling code here:
        jLabel8.setText(ganaMas());
        
    }                         

    private void unaCosaMas(java.awt.event.MouseEvent evt) {                            
        // TODO add your handling code here:
        lblempleado.setText("s´pkh");
    } 
    
    public String ganaMas(){
        
        
        return null;      
}
    
   
     
     
     
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_trabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_trabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_trabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_trabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_trabajadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbleee;
    private javax.swing.JLabel lblempleado;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JTable tbldatos;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JSpinner txthoras;
    private javax.swing.JTextField txtnombres;
    private javax.swing.JTextField txtsalario;
    // End of variables declaration//GEN-END:variables
}
